apiVersion: v1
kind: Service
metadata:
  name: editor-service-api-service
  namespace: peerprep
spec:
  selector:
    app: editor-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004
