FROM node:lts-hydrogen AS builder

WORKDIR /editor_service_docs
COPY . .
RUN npm install
RUN npm run build

FROM node:lts-hydrogen

WORKDIR /editor_service_docs

COPY --from=builder ./editor_service_docs/build .
COPY package.json .
COPY package-lock.json .

RUN npm install --omit=dev -y

CMD node main
